{% set name = "vbmicrolensing" %}
{% set version = "5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c604b7670fd7d99ec5177a95cebee3eee2d67c3a7ea3da87be88aa6eaa04248e


build:
  number: 0
  script:
    - export CMAKE_GENERATOR=Ninja  # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pybind11
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pip  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
  host:
    - python
    - pip
    - scikit-build-core >=0.10
    - pybind11
    - numpy
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - VBMicrolensing

about:
  home: https://github.com/valboz/VBMicrolensing
  summary: "Efficient computation in gravitational microlensing events using advanced contour integration."
  description: |
    VBMicrolensing is a tool for efficient computation in gravitational microlensing events using the advanced contour integration method, supporting single, binary and multiple lenses.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://github.com/valboz/VBMicrolensing
  dev_url: https://github.com/valboz/VBMicrolensing

extra:
  recipe-maintainers:
    - valboz
    - VitoSaggese
    - AmberLee2427
